version: '3'
services:
  client:
    build: client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    restart: always
    command: yarn start
    volumes: # This is where the magic happens!
      - ./client/src:/usr/src/client/src
      - ./client/public:/usr/src/client/public
  server:
    build: server
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3001:3001"
    restart: always
    command: yarn start
    volumes: # This is where the magic happens!
      - ./server:/usr/src/server
      - /usr/src/server/node_modules/